name: Trigger auto deployment for react-hook-demos

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/react-hook-demos-AutoDeployTrigger-0c42926e-d76a-423b-8434-23727db6f56b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REACTHOOKDEMOS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REACTHOOKDEMOS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REACTHOOKDEMOS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.REACTHOOKDEMOS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REACTHOOKDEMOS_REGISTRY_PASSWORD }}
          containerAppName: react-hook-demos
          resourceGroup: NicoFilips_group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


